#!/bin/bash
#: Title       : hw
#: Date        : 2021-3-14
#: Author      : "Chris F.A. Jhonson" <shell@cfajhonson.com>
#: Version     : 1.0
#: Description : Print Hello, World!
#: Options     : None

printf "%s\n" "Hello, World!" !"

